'use strict';
(() => {
const {$,clamp,esc,toast,copy,download,rgb,hex,fromHsl,bindColor,setColor,read,write,history,wireHistory,size,canvasBlob,fullScreen,readJSON}=Studio;
const patterns=[
 ['dots','Dots','Geometric','Evenly spaced dots with adjustable radius.'],['polka','Polka dots','Geometric','Alternating large and small dots.'],['staggered','Offset dots','Geometric','A classic half-drop dot arrangement.'],['stripes','Stripes','Geometric','Parallel bands; rotate to any angle.'],['diagonal','Diagonal lines','Geometric','Seamless diagonal strokes.'],['grid','Grid','Geometric','A precise square lattice.'],['checker','Checkerboard','Geometric','Alternating filled squares.'],['diamonds','Diamonds','Geometric','A repeating diamond lattice.'],['triangles','Triangles','Geometric','Alternating triangular facets.'],['hexagons','Honeycomb','Geometric','A hexagonal cell lattice.'],['cubes','Isometric cubes','Geometric','Three-tone geometric blocks.'],['chevron','Chevron','Geometric','Bold connected V-shaped bands.'],['zigzag','Zigzag','Geometric','Thin angular waves.'],['crosses','Crosses','Geometric','Small diagonal crosses.'],['pluses','Plus signs','Geometric','A field of simple plus motifs.'],['rings','Rings','Geometric','A regular array of open circles.'],['concentric','Concentric','Geometric','Nested circular linework.'],['arches','Arches','Geometric','Repeating architectural arch shapes.'],['scales','Fish scales','Geometric','Overlapping, scalloped scale outlines.'],
 ['gingham','Gingham','Textile','Translucent horizontal and vertical bands.'],['plaid','Plaid','Textile','Intersecting bands of varied width.'],['tartan','Tartan','Textile','Layered bands and fine contrasting lines.'],['herringbone','Herringbone','Textile','Alternating diagonal strokes in a broken zigzag.'],['basket','Basket weave','Textile','Interlocking bundles of horizontal and vertical strands.'],['weave','Woven grid','Textile','Fine alternating over-and-under ribbons.'],['houndstooth','Houndstooth','Textile','A stylized broken-check textile motif.'],['argyle','Argyle','Textile','Contrasting diamonds crossed by fine diagonals.'],['pinstripe','Pinstripe','Textile','Alternating fine and wide vertical stripes.'],['tweed','Tweed','Textile','Seeded short threads in two colors.'],['knit','Knit','Textile','Paired loops resembling knitted stitches.'],['stitch','Running stitch','Textile','Dashed lines resembling hand stitching.'],
 ['waves','Waves','Organic','Flowing, repeating wave ribbons.'],['sine','Sine lines','Organic','Smooth periodic curves with adjustable line weight.'],['scallops','Scallops','Organic','Stacked fan-shaped curves.'],['terrazzo','Terrazzo','Organic','Seeded irregular chips scattered across the tile.'],['confetti','Confetti','Organic','Randomized colorful fragments and small strokes.'],['noise','Grain / noise','Organic','Seeded vector grain; density controls the number of specks.'],['speckle','Speckle','Organic','Random organic dots of varied sizes.'],['bubbles','Bubbles','Organic','Seeded circles with translucent accents.'],['pebbles','Pebbles','Organic','Scattered irregular rounded stones.'],['woodgrain','Wood grain','Organic','Stylized wavy contours and knots.'],['topographic','Topographic','Organic','Stylized periodic contour lines with varying elevations.'],
 ['stars','Stars','Decorative','Alternating four- and five-point stars.'],['hearts','Hearts','Decorative','A two-color half-drop heart motif.'],['flowers','Flowers','Floral','Five-petal blooms with a leaf, on a half-drop.'],['leaves','Leaves','Floral','Paired leaves arranged along diagonal stems.'],['quatrefoil','Quatrefoil','Decorative','A four-lobed ornamental lattice.'],['moroccan','Moroccan tile','Decorative','Stylized ornamental pointed tile outlines.'],['greekkey','Greek key','Decorative','A squared meander border repeated in rows.'],['maze','Maze','Decorative','Seeded right-angle paths in a tiled maze texture.'],['truchet','Truchet arcs','Decorative','Seeded quarter-circle tiles; the outer edges wrap.'],['sunburst','Sunburst','Decorative','Radial rays repeated in a grid.'],['circuit','Circuit board','Decorative','Orthogonal paths with circular connection points.'],
 ['brick','Brickwork','Geometric','Running-bond brick courses.'],['crosshatch','Crosshatch','Geometric','Two crossing families of fine diagonals.'],['lattice','Diamond lattice','Geometric','An open trellis of diamond outlines.'],['octagons','Octagons','Geometric','Truncated-square tiling with diamond joints.'],['halftone','Halftone','Geometric','Dots that swell and shrink across the tile.'],['pindot','Pin dots','Geometric','Very fine half-drop dots.'],['nested','Nested squares','Geometric','Concentric square outlines.'],['harlequin','Harlequin','Geometric','Bold alternating filled diamonds.'],['steps','Staircase','Geometric','Two-tone blocks climbing diagonally.'],['quartercircles','Quarter circles','Geometric','Filled quarter discs in alternating tones.'],['pinwheel','Pinwheel','Geometric','Four triangles spinning about the centre.'],['dashgrid','Dashed grid','Geometric','A grid drawn in dashes rather than solid rules.'],['ogee','Ogee','Geometric','The classic onion-shaped lattice.'],['trigrid','Triangle grid','Geometric','Horizontal rules crossed by opposing diagonals.'],
 ['twill','Twill','Textile','The stepped diagonal float of a twill weave.'],['corduroy','Corduroy','Textile','Vertical ribs with a shaded channel between.'],['windowpane','Windowpane','Textile','Widely spaced check on a fine secondary rule.'],['buffalo','Buffalo check','Textile','Large translucent overlapping check.'],['glencheck','Glen check','Textile','Prince-of-Wales blocks of fine crossing lines.'],['ticking','Ticking stripe','Textile','Mattress-ticking pairs of heavy and hairline stripes.'],['cable','Cable knit','Textile','Interlacing cables like a knitted panel.'],['lace','Lace','Textile','Scalloped edging above a field of eyelets.'],['burlap','Burlap','Textile','Coarse open weave with slubs.'],['patchwork','Patchwork','Textile','Quilt blocks of alternating piecing.'],
 ['clouds','Clouds','Organic','Soft stacked cumulus shapes.'],['raindrops','Raindrops','Organic','Seeded teardrops scattered across the tile.'],['marble','Marble veins','Organic','Fine drifting veins of varying weight.'],['ripples','Ripples','Organic','Seeded concentric rings, like rain on water.'],['crackle','Crackle','Organic','Craquelure: random branching fractures.'],['cells','Cells','Organic','Overlapping organic cell walls.'],['feathers','Feathers','Organic','Paired plumes with fine barbs.'],['branches','Branches','Organic','Seeded twigs with side shoots.'],['dunes','Dunes','Organic','Long undulating sand ridges.'],['splatter','Splatter','Organic','Ink spatter with fine satellite droplets.'],
 ['damask','Damask','Decorative','A formal mirrored damask motif on a half-drop.'],['fleur','Fleur-de-lis','Decorative','The heraldic lily, repeated on a half-drop.'],['paisley','Paisley','Decorative','Curled boteh droplets facing alternate ways.'],['mandala','Mandala','Decorative','Radiating spokes and beads around a rosette.'],['snowflakes','Snowflakes','Decorative','Six-armed crystals in four sizes.'],['celestial','Celestial','Decorative','Sun, crescent moon and scattered stars.'],['deco','Art deco fan','Decorative','Stacked fan arcs in the deco manner.'],['rosette','Rosette','Decorative','Interlocking six-circle rosettes.'],['clover','Clover','Decorative','Four-lobed clover outlines.'],['laurel','Laurel','Decorative','Leafed garlands running in bands.'],
 ['memphis','Memphis','Retro','Eighties squiggles, confetti and loose shapes.'],['groovy','Groovy waves','Retro','Thick seventies undulations.'],['atomic','Atomic','Retro','Mid-century starbursts on a diagonal set.'],['bauhaus','Bauhaus','Retro','Primary blocks, quarter discs and circles.'],['mod','Mod flowers','Retro','Sixties six-petal rosettes.'],['vaporgrid','Vapor grid','Retro','A perspective horizon grid.'],['checkerwave','Wavy check','Retro','A checkerboard rippling out of alignment.'],['sunsetarcs','Sunset arcs','Retro','Concentric arcs rising from the baseline.'],
 ['pixels','Pixel blocks','Tech','Seeded eight-bit blocks.'],['binary','Binary','Tech','A field of ones and zeros.'],['isogrid','Isometric grid','Tech','Three-axis isometric construction lines.'],['wireframe','Wireframe','Tech','Boxed diagonals with node points.'],['qrcode','Code blocks','Tech','A seeded scan-code texture with a finder eye.'],['nodes','Network','Tech','Seeded nodes joined into a chain.'],['barcode','Barcode','Tech','Vertical bars of seeded width.'],['datastream','Data stream','Tech','Dashed columns falling like a data feed.'],
 ['ditsy','Ditsy floral','Floral','Tiny scattered blooms and leaves — the classic dress print.'],['daisy','Daisies','Floral','Eight-petal daisies in two sizes.'],['rosebud','Roses','Floral','Spiralled rosebuds on a half-drop.'],['tulip','Tulips','Floral','Upright tulips with paired leaves.'],['sakura','Cherry blossom','Floral','Five-petal blossoms with fine stamens.'],['sunflower','Sunflowers','Floral','Broad ray petals around a seeded disc.'],['poppy','Poppies','Floral','Four cupped petals around a dark eye.'],['lotus','Lotus','Floral','Layered lotus petals in outline.'],['vine','Trailing vine','Floral','A meandering stem with leaves and berries.'],['meadow','Wildflower meadow','Floral','Seeded stems of varying height, as in a meadow.'],['chintz','Chintz','Floral','Dense all-over blooms and foliage.'],['morris','Arts & Crafts','Floral','Scrolling stems and rosettes in the Morris manner.'],['tropical','Tropical leaves','Floral','Large veined leaves at alternating angles.'],['lavender','Lavender','Floral','Slender sprigs of budded spikes.'],['blossom','Blossom branch','Floral','A branch carrying blossoms and small leaves.'],['posy','Posy','Floral','Small tied bouquets on a half-drop.'],
 ['custom','Custom motif','Custom','Choose a shape or short text, then repeat it in a grid, half-drop, or seeded scatter.']
];
// Chips are derived from the table above: a new category appears on its own.
const CATEGORY_ORDER=['Floral','Geometric','Textile','Organic','Decorative','Retro','Tech'];
function categoryList(){const found=[...new Set(patterns.map(p=>p[2]))];const known=CATEGORY_ORDER.filter(c=>found.includes(c));const extra=found.filter(c=>!CATEGORY_ORDER.includes(c)&&c!=='Custom');return ['All',...known,...extra,...(found.includes('Custom')?['Custom']:[])];}
const initial={version:1,tool:'pattern-studio',pattern:'gingham',foreground:'#bd643f',background:'#f9eddb',accent:'#e1af7a',transparent:false,opacity:100,scale:80,rotation:0,weight:8,density:6,spacing:0,mirror:false,offsetX:0,offsetY:0,seed:42,customShape:'star',customText:'✦',customLayout:'grid'};
let s=structuredClone(initial),category='All',format='css',zoom=1,saved=read('bt-pattern-saved',[]);if(!Array.isArray(saved))saved=[];
const schemes=[['Terracotta','#bd643f','#f9eddb','#e1af7a'],['Indigo','#3c547c','#e9edf4','#8ca4c9'],['Botanical','#4e6a52','#eceddd','#9dae82'],['Rose','#a45468','#f7e9e5','#d79fa4'],['Monochrome','#292b2a','#f4f3ee','#91958c'],['Mustard','#a47e27','#fcf4d9','#d5bb71'],['Lavender','#75618c','#f2edf6','#b4a2cd'],['Night','#93b8ad','#20373b','#4f8279']];
const ranges={opacity:[0,100],scale:[12,300],rotation:[0,360],weight:[1,24],density:[2,18],spacing:[0,60],offsetX:[-300,300],offsetY:[-300,300],seed:[1,999999]};
function validate(v){if(!v||v.tool!=='pattern-studio'||v.version!==1||!patterns.some(p=>p[0]===v.pattern)||!['foreground','background','accent'].every(k=>typeof v[k]==='string'&&/^#[0-9a-f]{6}$/i.test(v[k]))||!['circle','square','diamond','triangle','star','cross','heart','hexagon','text'].includes(v.customShape)||!['grid','brick','scatter'].includes(v.customLayout)||typeof v.customText!=='string'||v.customText.length>8)throw Error();for(const [k,[lo,hi]] of Object.entries(ranges))if(!Number.isFinite(v[k])||v[k]<lo||v[k]>hi)throw Error();return {...Object.fromEntries(Object.keys(initial).map(k=>[k,v[k]])),mirror:!!v.mirror,transparent:!!v.transparent};}
const hist=history(()=>s,apply);wireHistory(hist);function apply(v){s=validate(v);sync();render();renderLibrary();}
function rng(seed){let a=seed>>>0;return ()=>{a+=0x6D2B79F5;let t=a;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return ((t^t>>>14)>>>0)/4294967296;};}
// Each recipe is a 100 x 100 vector motif. Nine neighboring copies wrap edge-crossing shapes.
function motif(v){const f=v.foreground,a=v.accent,w=v.weight,n=Math.round(v.density),rand=rng(v.seed);let out='';const add=x=>out+=x;
 const rect=(x,y,b,h,c=f,opacity=1)=>`<rect x="${x}" y="${y}" width="${b}" height="${h}" fill="${c}" opacity="${opacity}"/>`;
 const circle=(x,y,r,c=f,stroke='none',sw=w)=>`<circle cx="${x}" cy="${y}" r="${r}" fill="${c}" stroke="${stroke}" stroke-width="${sw}"/>`;
 const path=(d,c='none',stroke=f,sw=w,extra='')=>`<path d="${d}" fill="${c}" stroke="${stroke}" stroke-width="${sw}" stroke-linecap="round" stroke-linejoin="round" ${extra}/>`;
 const poly=(pts,c=f)=>`<polygon points="${pts}" fill="${c}"/>`;
 const star=(x,y,r,points=5,c=f)=>{let pts=[];for(let i=0;i<points*2;i++){const t=i*Math.PI/points-Math.PI/2,rr=i%2?r*.42:r;pts.push(`${x+Math.cos(t)*rr},${y+Math.sin(t)*rr}`);}return poly(pts.join(' '),c);};
 const heart=(x,y,z,c=f)=>`<g transform="translate(${x} ${y}) scale(${z/30})">${path('M0 10 C-40 -12 -15 -36 0 -17 C15 -36 40 -12 0 10',c,'none')}</g>`;
 const wave=(y,amp,stroke=f,sw=w)=>path(`M0 ${y} C25 ${y-amp} 25 ${y-amp} 50 ${y} S75 ${y+amp} 100 ${y}`,'none',stroke,sw);
 switch(v.pattern){
 case 'dots':add(circle(50,50,w*1.9));break;
 case 'polka':add(circle(25,25,w*1.5));add(circle(75,75,w*.75,a));break;
 case 'staggered':for(const [x,y] of [[0,25],[50,25],[25,75],[75,75]])add(circle(x,y,w));break;
 case 'stripes':add(rect(0,25,100,w*2));add(rect(0,75,100,w,a));break;
 case 'diagonal':add(path('M0 100 L100 0'));add(path('M-50 100 L50 0 M50 100 L150 0','none',a,w/2));break;
 case 'grid':add(path('M0 0 H100 V100 H0 Z','none',f,w/2));add(path('M50 0 V100 M0 50 H100','none',a,w/4));break;
 case 'checker':add(rect(0,0,50,50));add(rect(50,50,50,50));break;
 case 'diamonds':add(poly('50,0 100,50 50,100 0,50'));add(poly('50,20 80,50 50,80 20,50',a));break;
 case 'triangles':add(poly('0,0 100,0 50,50'));add(poly('0,100 100,100 50,50',a));break;
 case 'hexagons':for(const [x,y] of [[25,0],[75,50],[25,100]])add(path(`M${x-25} ${y} l12.5 -25 h25 l12.5 25 -12.5 25 h-25 Z`,'none',f,w/3));break;
 case 'cubes':for(const [x,y] of [[0,0],[50,50],[100,0],[0,100],[100,100]]){add(poly(`${x},${y-30} ${x+25},${y-15} ${x},${y} ${x-25},${y-15}`,a));add(poly(`${x-25},${y-15} ${x},${y} ${x},${y+30} ${x-25},${y+15}`));add(poly(`${x},${y} ${x+25},${y-15} ${x+25},${y+15} ${x},${y+30}`,v.background));}break;
 case 'chevron':for(let y=0;y<=100;y+=50)add(path(`M0 ${y+25} L25 ${y} L50 ${y+25} L75 ${y} L100 ${y+25}`,'none',y===50?a:f,w*1.4));break;
 case 'zigzag':for(let y=0;y<100;y+=25)add(path(`M0 ${y} l12.5 12.5 12.5 -12.5 12.5 12.5 12.5 -12.5 12.5 12.5 12.5 -12.5 12.5 12.5 12.5 -12.5`,'none',f,w/3));break;
 case 'crosses':add(path('M15 15 L35 35 M35 15 L15 35'));add(path('M65 65 L85 85 M85 65 L65 85','none',a,w));break;
 case 'pluses':add(path('M25 10 V40 M10 25 H40'));add(path('M75 60 V90 M60 75 H90','none',a,w));break;
 case 'rings':add(circle(50,50,25,'none',f,w/2));break;
 case 'concentric':for(let i=1;i<=n;i++)add(circle(50,50,i*45/n,'none',i%2?f:a,Math.min(w/3,40/n)));break;
 case 'arches':for(const x of [0,50])add(path(`M${x} 100 V25 A25 25 0 0 1 ${x+50} 25 V100`,'none',f,w/2));break;
 case 'scales':for(const [x,y] of [[0,0],[50,0],[25,50],[75,50]])add(path(`M${x-25} ${y} a25 25 0 0 0 50 0`,'none',f,w/2));break;
 case 'gingham':add(rect(0,0,50,100,f,.48));add(rect(0,0,100,50,f,.48));break;
 case 'plaid':add(rect(10,0,28,100,f,.6));add(rect(0,10,100,28,f,.6));add(rect(60,0,w,100,a));add(rect(0,60,100,w,a));add(path('M45 0 V100 M0 45 H100','none',f,2));break;
 case 'tartan':for(const x of [0,50]){add(rect(x,0,25,100,f,.6));add(rect(0,x,100,25,f,.6));add(rect(x+10,0,5,100,a,.8));add(rect(0,x+10,100,5,a,.8));}add(path('M35 0 V100 M85 0 V100 M0 35 H100 M0 85 H100','none',a,Math.max(1,w/4)));break;
 case 'herringbone':for(let y=-25;y<100;y+=25)for(let x=0;x<100;x+=50){add(path(`M${x} ${y} l25 25 v20 l-25 -25 Z`,f,'none'));add(path(`M${x+25} ${y+25} l25 -25 v20 l-25 25 Z`,a,'none'));}break;
 case 'basket':for(const [x,y] of [[0,0],[50,50]])for(let i=0;i<3;i++){add(rect(x+i*15,y,10,45));add(rect((x+50)%100,y+i*15,45,10,a));}break;
 case 'weave':for(let i=0;i<5;i++){add(rect(i*20,0,10,100,f,.65));add(rect(0,i*20,100,10,a,.65));for(let j=0;j<5;j++)if((i+j)%2===0)add(rect(i*20,j*20,10,10));}break;
 case 'houndstooth':for(const [x,y] of [[0,0],[50,50]])add(`<g transform="translate(${x} ${y})">${poly('0,12.5 12.5,0 25,12.5 37.5,0 37.5,25 50,37.5 37.5,50 25,37.5 12.5,50 12.5,25 0,37.5')}</g>`);break;
 case 'argyle':add(poly('50,0 75,50 50,100 25,50'));add(poly('0,0 25,50 0,100 -25,50',a));add(path('M0 25 L50 125 L100 25 M0 75 L50 -25 L100 75','none',a,Math.max(1,w/4),'stroke-dasharray="4 3"'));break;
 case 'pinstripe':for(let x=0;x<100;x+=25){add(rect(x,0,Math.max(1,w/4),100));add(rect(x+7,0,1,100,a));}break;
 case 'tweed':for(let i=0;i<n*10;i++){const x=rand()*100,y=rand()*100;add(path(`M${x} ${y} l${rand()*12+3} ${rand()*6-3}`,'none',i%3?a:f,w/5));}break;
 case 'knit':for(let y=0;y<100;y+=25)for(let x=0;x<100;x+=25){add(path(`M${x+12.5} ${y+24} C${x-7} ${y+10} ${x+2} ${y-5} ${x+12.5} ${y+24} C${x+32} ${y+10} ${x+23} ${y-5} ${x+12.5} ${y+24}`,'none',f,w/3));}break;
 case 'stitch':for(let y=12.5;y<100;y+=25)add(path(`M0 ${y} H100`,'none',f,w/3,'stroke-dasharray="12 13"'));break;
 case 'waves':for(let y=0;y<100;y+=25)add(wave(y,20,y%50?f:a,w));break;
 case 'sine':for(let i=0;i<n;i++)add(wave(i*100/n,18,f,Math.min(w/3,50/n)));break;
 case 'scallops':for(const [x,y] of [[0,0],[50,0],[25,50],[75,50]])for(let r=10;r<=25;r+=5)add(path(`M${x-r} ${y} a${r} ${r} 0 0 0 ${r*2} 0`,'none',f,w/4));break;
 case 'terrazzo':for(let i=0;i<n*3;i++){const x=rand()*100,y=rand()*100,r=2+rand()*w,pts=[];for(let k=0;k<5;k++){const t=k*Math.PI*2/5,rr=r*(.5+rand()*.5);pts.push(`${x+Math.cos(t)*rr},${y+Math.sin(t)*rr}`);}add(poly(pts.join(' '),i%3?f:a));}break;
 case 'confetti':for(let i=0;i<n*4;i++){const x=rand()*100,y=rand()*100,t=rand()*360;add(`<g transform="translate(${x} ${y}) rotate(${t})">${i%3?rect(-2,-5,w/3,w,i%2?f:a):circle(0,0,w/3,a)}</g>`);}break;
 case 'noise':for(let i=0;i<n*35;i++)add(circle(rand()*100,rand()*100,.15+rand()*w/8,i%3?f:a));break;
 case 'speckle':for(let i=0;i<n*8;i++)add(circle(rand()*100,rand()*100,.3+rand()*w/3,i%4?f:a));break;
 case 'bubbles':for(let i=0;i<n*2;i++)add(circle(rand()*100,rand()*100,3+rand()*w*1.8,i%3?'none':a,f,w/5));break;
 case 'pebbles':for(let i=0;i<n*2;i++){const x=rand()*100,y=rand()*100,z=.4+rand(),t=rand()*360;add(`<g transform="translate(${x} ${y}) rotate(${t}) scale(${z*w/8})">${path('M-8 -4 C-12 -15 10 -14 12 -2 C17 12 -12 15 -8 -4 Z',i%3?f:a,'none')}</g>`);}break;
 case 'woodgrain':for(let i=0;i<n*2;i++)add(wave(i*100/(n*2),8+8*Math.sin(i),i%3?f:a,Math.min(w/5,25/n)));add(`<ellipse cx="50" cy="50" rx="12" ry="5" fill="none" stroke="${f}" stroke-width="${w/4}"/>`);break;
 case 'topographic':for(let i=0;i<n*2;i++){const y=i*100/(n*2),amp=10+Math.sin(i*1.2)*9;add(path(`M0 ${y} C10 ${y-amp} 20 ${y+amp} 35 ${y} S60 ${y-amp} 75 ${y} S90 ${y+amp} 100 ${y}`,'none',i%4?f:a,Math.min(w/5,20/n)));}break;
 case 'stars':add(star(25,25,w*2,5));add(star(75,75,w*1.6,4,a));break;
 case 'hearts':add(heart(25,32,w*1.6));add(heart(75,82,w*1.6,a));break;
 case 'flowers':{const fl=(x,y,r,c)=>{let o='';for(let k=0;k<5;k++){const t=k*2*Math.PI/5-Math.PI/2;o+=path(`M${x} ${y} Q${x+Math.cos(t-.42)*r*1.2} ${y+Math.sin(t-.42)*r*1.2} ${x+Math.cos(t)*r} ${y+Math.sin(t)*r} Q${x+Math.cos(t+.42)*r*1.2} ${y+Math.sin(t+.42)*r*1.2} ${x} ${y} Z`,c,'none',0);}return o+circle(x,y,r*.26,v.background);};for(const [x,y,r,c] of [[25,25,w*1.7,f],[75,75,w*1.7,f],[75,25,w*1.1,a],[25,75,w*1.1,a]])add(fl(x,y,r,c));for(const [x,y] of [[50,50],[0,50],[100,50],[50,0],[50,100]])add(path(`M${x} ${y} q7 -6 11 -1 q-7 7 -11 1 Z`,a,'none',0));break;}
 case 'leaves':for(const [x,y] of [[10,10],[60,60]]){add(path(`M${x} ${y} l30 30`,'none',f,w/5));add(path(`M${x+15} ${y+15} q-25 0 -15 -20 q20 0 15 20`,f,'none'));add(path(`M${x+20} ${y+20} q0 -25 20 -15 q0 20 -20 15`,a,'none'));}break;
 case 'quatrefoil':add(path('M50 20 C20 -10 0 30 20 50 C-10 80 30 100 50 80 C80 110 100 70 80 50 C110 20 70 0 50 20 Z','none',f,w/2));break;
 case 'moroccan':add(path('M50 0 C50 20 25 15 25 35 C25 45 10 45 0 50 C10 55 25 55 25 65 C25 85 50 80 50 100 C50 80 75 85 75 65 C75 55 90 55 100 50 C90 45 75 45 75 35 C75 15 50 20 50 0 Z','none',f,w/3));break;
 case 'greekkey':for(let y=0;y<100;y+=50)add(path(`M0 ${y+5} H90 V${y+40} H20 V${y+20} H70 V${y+30} H35`,'none',f,w/2));break;
 case 'maze':for(let y=0;y<100;y+=20)for(let x=0;x<100;x+=20)add(path(rand()>.5?`M${x} ${y} h20 v20`:`M${x} ${y+20} v-20 h20`,'none',f,w/3));break;
 case 'truchet':for(let y=0;y<100;y+=25)for(let x=0;x<100;x+=25){const d=rand()>.5?`M${x+12.5} ${y} A12.5 12.5 0 0 1 ${x+25} ${y+12.5} M${x} ${y+12.5} A12.5 12.5 0 0 1 ${x+12.5} ${y+25}`:`M${x+12.5} ${y} A12.5 12.5 0 0 0 ${x} ${y+12.5} M${x+25} ${y+12.5} A12.5 12.5 0 0 0 ${x+12.5} ${y+25}`;add(path(d,'none',f,w/2));}break;
 case 'sunburst':for(let i=0;i<n*3;i++){const t=i*Math.PI*2/(n*3),x=Math.cos(t),y=Math.sin(t);add(path(`M${50+x*12} ${50+y*12} L${50+x*42} ${50+y*42}`,'none',i%2?f:a,w/3));}break;
 case 'circuit':add(path('M0 20 H30 L50 40 V100 M100 70 H75 L60 55 V0 M0 85 H20 V55 H35','none',f,w/3));for(const [x,y] of [[30,20],[75,70],[20,85],[35,55]])add(circle(x,y,w/2,v.background,f,w/4));break;
 case 'brick':for(let y=0;y<100;y+=25){const o=(y/25)%2?25:0;for(let x=-50;x<100;x+=50)add(rect(x+o+1.5,y+1.5,47,22,(y/25)%2?a:f));}break;
 case 'crosshatch':for(let i=-2;i<=2;i++){add(path(`M${i*50} 0 L${i*50+100} 100`,'none',f,w/3));add(path(`M${i*50} 100 L${i*50+100} 0`,'none',a,w/3));}break;
 case 'lattice':for(const [x,y] of [[0,0],[50,0],[100,0],[0,50],[50,50],[100,50],[0,100],[50,100],[100,100]])add(path(`M${x} ${y-22} L${x+22} ${y} L${x} ${y+22} L${x-22} ${y} Z`,'none',f,w/3));break;
 case 'octagons':{const oct=(x,y,r,c)=>poly(Array.from({length:8},(_,i)=>{const t=i*Math.PI/4+Math.PI/8;return `${x+Math.cos(t)*r},${y+Math.sin(t)*r}`;}).join(' '),c);for(const [x,y] of [[25,25],[75,25],[25,75],[75,75]])add(oct(x,y,23,f));for(const [x,y] of [[0,0],[50,0],[100,0],[0,50],[50,50],[100,50],[0,100],[50,100],[100,100]])add(poly(`${x},${y-8} ${x+8},${y} ${x},${y+8} ${x-8},${y}`,a));break;}
 case 'halftone':{const k=8;for(let i=0;i<k;i++)for(let j=0;j<k;j++){const x=(i+.5)*100/k,y=(j+.5)*100/k,g=.5+.5*Math.sin(x*Math.PI/50);add(circle(x,y,Math.max(.6,(w/2.4)*(.25+g)),i%2?f:a));}break;}
 case 'pindot':{const k=5,st=100/k;for(let j=0;j<k;j++)for(let i=0;i<k;i++)add(circle(i*st+(j%2?st/2:0),j*st,Math.max(.8,w/4),j%2?a:f));break;}
 case 'nested':for(let i=1;i<=n;i++){const d=i*48/n;add(path(`M${d} ${d} H${100-d} V${100-d} H${d} Z`,'none',i%2?f:a,Math.min(w/3,26/n)));}break;
 case 'harlequin':{add(poly('50,0 100,50 50,100 0,50',f));add(poly('0,0 50,50 0,100 -50,50',a));add(poly('100,0 150,50 100,100 50,50',a));break;}
 case 'steps':for(let i=0;i<4;i++){add(rect(i*25,i*25,25,25,f));add(rect(i*25+25,i*25,25,25,a));}break;
 case 'quartercircles':for(let y=0;y<100;y+=50)for(let x=0;x<100;x+=50)add(path(`M${x} ${y} L${x+50} ${y} A50 50 0 0 1 ${x} ${y+50} Z`,((x+y)/50)%2?a:f,'none',0));break;
 case 'pinwheel':{[[0,0,50,0],[100,0,100,50],[100,100,50,100],[0,100,0,50]].forEach((p,i)=>add(poly(`${p[0]},${p[1]} ${p[2]},${p[3]} 50,50`,i%2?a:f)));break;}
 case 'dashgrid':{add(path('M0 25 H100 M0 75 H100','none',f,w/3,'stroke-dasharray="9 7"'));add(path('M25 0 V100 M75 0 V100','none',a,w/3,'stroke-dasharray="9 7"'));break;}
 case 'ogee':{const cell=(x,y,c)=>path(`M${x} ${y} Q${x} ${y-30} ${x+25} ${y-30} Q${x+50} ${y-30} ${x+50} ${y} Q${x+50} ${y+30} ${x+25} ${y+30} Q${x} ${y+30} ${x} ${y} Z`,'none',c,w/2);for(const [x,y] of [[0,25],[50,25],[0,75],[50,75]])add(cell(x,y,(x+y)%100?a:f));break;}
 case 'trigrid':{for(let y=0;y<=100;y+=25)add(path(`M0 ${y} H100`,'none',f,w/4));for(let i=-2;i<=4;i++){add(path(`M${i*50} 0 L${i*50+50} 100`,'none',a,w/4));add(path(`M${i*50} 100 L${i*50+50} 0`,'none',a,w/4));}break;}
 case 'twill':{const st=12.5;for(let i=0;i<8;i++)for(let j=0;j<8;j++)if((i+j)%4<2)add(rect(i*st,j*st,st,st,(i+j)%8<4?f:a,.9));break;}
 case 'corduroy':for(let x=0;x<100;x+=12.5){add(rect(x,0,9,100,f,.8));add(rect(x+9,0,3.5,100,a,.5));}break;
 case 'windowpane':{add(path('M0 0 H100 M0 0 V100','none',f,w/2));add(path('M50 0 V100 M0 50 H100','none',a,Math.max(1,w/5)));break;}
 case 'buffalo':{add(rect(0,0,50,100,f,.6));add(rect(0,0,100,50,f,.6));add(rect(50,50,50,50,a,.35));break;}
 case 'glencheck':{for(let i=0;i<4;i++){add(rect(i*25,0,3,100,f,.5));add(rect(0,i*25,100,3,f,.5));}for(let i=0;i<8;i++){add(rect(i*12.5+6,0,1.5,100,a,.6));add(rect(0,i*12.5+6,100,1.5,a,.6));}add(rect(0,0,25,25,f,.22));add(rect(50,50,25,25,f,.22));break;}
 case 'ticking':for(let x=0;x<100;x+=25){add(rect(x,0,Math.max(1,w/2),100,f));add(rect(x+w/2+3,0,Math.max(1,w/5),100,a,.8));}break;
 case 'cable':for(let x=12.5;x<100;x+=25)for(let y=0;y<100;y+=25){add(path(`M${x-8} ${y} C${x-8} ${y+12} ${x+8} ${y+13} ${x+8} ${y+25}`,'none',f,w/2));add(path(`M${x+8} ${y} C${x+8} ${y+12} ${x-8} ${y+13} ${x-8} ${y+25}`,'none',a,w/2));}break;
 case 'lace':{for(let y=0;y<100;y+=25)add(path(`M0 ${y} q12.5 16 25 0 t25 0 t25 0 t25 0`,'none',f,w/3));for(let y=12.5;y<100;y+=25)for(let x=12.5;x<100;x+=25)add(circle(x,y,Math.max(1.5,w/2.5),'none',a,Math.max(1,w/5)));break;}
 case 'burlap':{for(let i=0;i<10;i++){add(rect(i*10,0,5,100,f,.32));add(rect(0,i*10,100,5,a,.32));}for(let i=0;i<n*8;i++)add(rect(rand()*100,rand()*100,2.5,1,f,.4));break;}
 case 'patchwork':[[0,0],[50,0],[0,50],[50,50]].forEach(([x,y],i)=>{add(rect(x,y,50,50,i%3?a:f,.45));if(i%2)add(poly(`${x},${y} ${x+50},${y} ${x},${y+50}`,f));else add(path(`M${x} ${y+25} h50 M${x+25} ${y} v50`,'none',f,Math.max(1,w/4)));});break;
 case 'clouds':for(const [x,y,z,c] of [[25,32,1,f],[75,72,.75,a],[62,20,.5,a]]){add(circle(x,y,14*z,c));add(circle(x+13*z,y+4*z,10*z,c));add(circle(x-13*z,y+4*z,9*z,c));add(rect(x-13*z,y+4*z,26*z,10*z,c));}break;
 case 'raindrops':for(let i=0;i<n*3;i++){const x=rand()*100,y=rand()*100,r=w*.55+rand()*w*.5;add(path(`M${x} ${y-r*1.7} C${x+r} ${y-r*.2} ${x+r*.7} ${y+r} ${x} ${y+r} C${x-r*.7} ${y+r} ${x-r} ${y-r*.2} ${x} ${y-r*1.7} Z`,i%3?f:a,'none',0));}break;
 case 'marble':for(let i=0;i<n;i++){const y=rand()*100;add(path(`M0 ${y} C25 ${y-12+rand()*8} 40 ${y+14-rand()*8} 60 ${y+2} S90 ${y-10} 100 ${y}`,'none',i%3?a:f,Math.max(.6,w/(3+rand()*5))));}break;
 case 'ripples':for(let i=0;i<n;i++){const x=rand()*100,y=rand()*100;for(let k=1;k<=3;k++)add(circle(x,y,k*w*.9,'none',k%2?f:a,Math.max(.6,w/6)));}break;
 case 'crackle':for(let i=0;i<n*5;i++){const x=rand()*100,y=rand()*100;add(path(`M${x} ${y} l${rand()*34-17} ${rand()*34-17} l${rand()*28-14} ${rand()*28-14}`,'none',i%4?f:a,Math.max(.6,w/4)));}break;
 case 'cells':for(let i=0;i<n;i++)add(circle(rand()*100,rand()*100,8+rand()*14,'none',i%3?f:a,Math.max(.8,w/3)));break;
 case 'feathers':for(const [x,y,c] of [[25,25,f],[75,75,a]]){add(path(`M${x} ${y-22} C${x+14} ${y-6} ${x+10} ${y+14} ${x} ${y+22} C${x-10} ${y+14} ${x-14} ${y-6} ${x} ${y-22} Z`,'none',c,w/3));add(path(`M${x} ${y-20} V${y+20}`,'none',c,Math.max(1,w/4)));for(let k=-14;k<=14;k+=6)add(path(`M${x} ${y+k} l7 -4 M${x} ${y+k} l-7 -4`,'none',c,Math.max(.5,w/6)));}break;
 case 'branches':for(let i=0;i<n*2;i++){const x=rand()*100,y=rand()*100,g=rand()*Math.PI*2,L=14+rand()*14,x2=x+Math.cos(g)*L,y2=y+Math.sin(g)*L,mx=(x+x2)/2,my=(y+y2)/2;add(path(`M${x} ${y} L${x2} ${y2}`,'none',f,Math.max(.8,w/3)));add(path(`M${mx} ${my} l${Math.cos(g+1)*7} ${Math.sin(g+1)*7} M${mx} ${my} l${Math.cos(g-1)*7} ${Math.sin(g-1)*7}`,'none',a,Math.max(.6,w/4)));}break;
 case 'dunes':for(let i=0;i<n;i++){const y=i*100/n;add(path(`M0 ${y} C20 ${y-9} 30 ${y+9} 50 ${y} S80 ${y-9} 100 ${y}`,'none',i%2?f:a,Math.max(.8,w/2.5)));}break;
 case 'splatter':for(let i=0;i<n*4;i++){const x=rand()*100,y=rand()*100;add(circle(x,y,rand()*w*.7+.6,i%3?f:a));if(i%4===0)for(let k=0;k<3;k++)add(circle(x+rand()*16-8,y+rand()*16-8,rand()*1.6+.4,a));}break;
 case 'damask':{const dm=(x,y,c)=>`<g transform="translate(${x} ${y})">${path('M0 -26 C14 -16 20 -4 12 6 C22 4 26 12 20 20 C12 28 2 24 0 16 C-2 24 -12 28 -20 20 C-26 12 -22 4 -12 6 C-20 -4 -14 -16 0 -26 Z','none',c,Math.max(1,w/3))}</g>`;add(dm(50,50,f));for(const [x,y] of [[0,0],[100,0],[0,100],[100,100]])add(dm(x,y,a));break;}
 case 'fleur':{const fl=(x,y,c)=>`<g transform="translate(${x} ${y})">${path('M0 20 V-4 M0 -4 C-10 -10 -12 -22 0 -26 C12 -22 10 -10 0 -4 M0 6 C-14 4 -20 -6 -16 -14 C-8 -12 -4 -4 0 6 M0 6 C14 4 20 -6 16 -14 C8 -12 4 -4 0 6 M-9 14 H9','none',c,Math.max(1,w/3))}</g>`;add(fl(50,50,f));for(const [x,y] of [[0,0],[100,0],[0,100],[100,100]])add(fl(x,y,a));break;}
 case 'paisley':{const ps=(x,y,c,r)=>`<g transform="translate(${x} ${y}) rotate(${r})">${path('M0 22 C-16 14 -18 -6 -6 -16 C4 -24 18 -18 18 -6 C18 4 8 8 2 4 C-4 0 -2 -8 4 -8','none',c,Math.max(1,w/3))}${circle(0,10,Math.max(1,w/2.5),c)}</g>`;add(ps(28,30,f,0));add(ps(78,80,a,180));break;}
 case 'mandala':{const k=Math.max(6,n*2);for(let i=0;i<k;i++){const t=i*Math.PI*2/k;add(path(`M${50+Math.cos(t)*10} ${50+Math.sin(t)*10} L${50+Math.cos(t)*34} ${50+Math.sin(t)*34}`,'none',i%2?f:a,Math.max(.8,w/4)));add(circle(50+Math.cos(t)*38,50+Math.sin(t)*38,Math.max(1,w/3),i%2?a:f));}add(circle(50,50,10,'none',f,Math.max(1,w/3)));add(circle(50,50,24,'none',a,Math.max(.8,w/5)));break;}
 case 'snowflakes':{const sf=(x,y,r,c)=>{let d='';for(let k=0;k<6;k++){const t=k*Math.PI/3,ax=x+Math.cos(t)*r,ay=y+Math.sin(t)*r,bx=x+Math.cos(t)*r*.6,by=y+Math.sin(t)*r*.6;d+=`M${x} ${y} L${ax} ${ay} M${bx} ${by} l${Math.cos(t+.9)*r*.3} ${Math.sin(t+.9)*r*.3} M${bx} ${by} l${Math.cos(t-.9)*r*.3} ${Math.sin(t-.9)*r*.3}`;}return path(d,'none',c,Math.max(.8,w/4));};add(sf(25,25,16,f));add(sf(75,75,12,a));add(sf(75,25,9,a));add(sf(25,75,9,f));break;}
 case 'celestial':{add(circle(28,30,12,'none',f,Math.max(1,w/3)));for(let k=0;k<8;k++){const t=k*Math.PI/4;add(path(`M${28+Math.cos(t)*16} ${30+Math.sin(t)*16} L${28+Math.cos(t)*21} ${30+Math.sin(t)*21}`,'none',f,Math.max(1,w/4)));}add(path('M78 62 A13 13 0 1 0 78 88 A10 10 0 1 1 78 62 Z',a,'none',0));add(star(20,78,6,5,a));add(star(62,16,4,4,f));break;}
 case 'deco':for(const [x,y,c] of [[0,100,f],[100,100,a],[50,0,a]])for(let k=1;k<=4;k++)add(path(`M${x-k*12} ${y} A${k*12} ${k*12} 0 0 1 ${x+k*12} ${y}`,'none',c,Math.max(1,w/3)));break;
 case 'rosette':for(const [x,y] of [[0,0],[50,50],[100,0],[0,100],[100,100]])for(let k=0;k<6;k++){const t=k*Math.PI/3;add(circle(x+Math.cos(t)*10,y+Math.sin(t)*10,10,'none',k%2?a:f,Math.max(.8,w/4)));}break;
 case 'clover':{const cl=(x,y,c)=>{let o='';for(let k=0;k<4;k++){const t=k*Math.PI/2;o+=circle(x+Math.cos(t)*9,y+Math.sin(t)*9,9,'none',c,Math.max(.8,w/4));}return o;};add(cl(25,25,f));add(cl(75,75,f));add(cl(75,25,a));add(cl(25,75,a));break;}
 case 'laurel':for(const y of [25,75]){add(path(`M0 ${y} H100`,'none',f,Math.max(1,w/4)));for(let x=4;x<100;x+=12){add(path(`M${x} ${y} q6 -7 12 -2 q-7 6 -12 2 Z`,f,'none',0));add(path(`M${x} ${y} q6 7 12 2 q-7 -6 -12 -2 Z`,a,'none',0));}}break;
 case 'memphis':{add(path('M6 20 q10 -14 20 0 t20 0','none',f,Math.max(2,w/2)));add(path('M54 78 q10 -14 20 0 t20 0','none',a,Math.max(2,w/2)));add(circle(80,24,Math.max(3,w*1.3),a));add(poly('20,62 34,86 6,86',f));add(rect(46,38,14,14,f));for(let i=0;i<6;i++)add(circle(12+i*6,52,1.8,a));break;}
 case 'groovy':for(let i=0;i<n;i++){const y=i*100/n;add(path(`M0 ${y} C25 ${y-16} 25 ${y+16} 50 ${y} S75 ${y-16} 100 ${y}`,'none',i%2?f:a,Math.max(2,w)));}break;
 case 'atomic':for(const [x,y,c] of [[25,25,f],[75,75,a],[75,25,a],[25,75,f]]){for(let k=0;k<4;k++){const t=k*Math.PI/4;add(path(`M${x-Math.cos(t)*13} ${y-Math.sin(t)*13} L${x+Math.cos(t)*13} ${y+Math.sin(t)*13}`,'none',c,Math.max(1,w/4)));}add(circle(x,y,Math.max(1.5,w/2),c));}break;
 case 'bauhaus':{add(rect(0,0,50,50,f));add(path('M50 0 A50 50 0 0 1 100 50 L50 50 Z',a,'none',0));add(circle(25,75,22,a));add(poly('50,100 100,100 100,50',f));break;}
 case 'mod':for(const [x,y,c] of [[25,25,f],[75,75,f],[75,25,a],[25,75,a]]){for(let k=0;k<6;k++){const t=k*Math.PI/3;add(circle(x+Math.cos(t)*8,y+Math.sin(t)*8,7,c));}add(circle(x,y,5,v.background));}break;
 case 'vaporgrid':{for(let i=0;i<=10;i++)add(path(`M${i*10} 100 L50 0`,'none',f,Math.max(.6,w/5)));for(let i=1;i<=n;i++){const y=100-100/Math.pow(1.35,i);add(path(`M0 ${y} H100`,'none',a,Math.max(.6,w/5)));}break;}
 case 'checkerwave':for(let j=0;j<8;j++)for(let i=0;i<8;i++){if((i+j)%2)continue;add(rect(i*12.5,j*12.5+Math.sin(i*Math.PI/4)*4,12.5,12.5,j%3?f:a,.9));}break;
 case 'sunsetarcs':for(let k=n;k>=1;k--)add(path(`M${50-k*11} 100 A${k*11} ${k*11} 0 0 1 ${50+k*11} 100 Z`,k%2?f:a,'none',0));break;
 case 'pixels':{const k=8,st=100/k;for(let j=0;j<k;j++)for(let i=0;i<k;i++){const r=rand();if(r>.62)add(rect(i*st,j*st,st,st,r>.85?a:f,.9));}break;}
 case 'binary':for(let j=0;j<6;j++)for(let i=0;i<6;i++)add(`<text x="${i*100/6+2}" y="${j*100/6+13}" font-family="monospace" font-size="${Math.max(6,w*1.3)}" fill="${rand()>.5?f:a}">${rand()>.5?'1':'0'}</text>`);break;
 case 'isogrid':{for(let i=-2;i<=4;i++){add(path(`M${i*50} 0 L${i*50+100} 50`,'none',f,Math.max(.6,w/4)));add(path(`M${i*50} 50 L${i*50+100} 0`,'none',a,Math.max(.6,w/4)));}for(let x=0;x<=100;x+=50)add(path(`M${x} 0 V100`,'none',f,Math.max(.6,w/5)));break;}
 case 'wireframe':{add(path('M0 0 H100 V100 H0 Z','none',f,Math.max(.8,w/4)));add(path('M0 0 L100 100 M100 0 L0 100','none',a,Math.max(.6,w/5)));add(path('M50 0 V100 M0 50 H100','none',f,Math.max(.5,w/6)));for(const [x,y] of [[0,0],[50,0],[100,0],[0,50],[50,50],[100,50],[0,100],[50,100],[100,100]])add(circle(x,y,Math.max(1,w/3),a));break;}
 case 'qrcode':{const k=7,st=100/k;for(let j=0;j<k;j++)for(let i=0;i<k;i++)if(rand()>.45)add(rect(i*st,j*st,st,st,f));add(rect(2,2,st*2.2,st*2.2,f));add(rect(2+st*.55,2+st*.55,st*1.1,st*1.1,v.background));add(rect(2+st*.8,2+st*.8,st*.6,st*.6,a));break;}
 case 'nodes':{const pts=Array.from({length:Math.max(3,n)},()=>[rand()*100,rand()*100]);pts.forEach((p,i)=>{const q=pts[(i+1)%pts.length];add(path(`M${p[0]} ${p[1]} L${q[0]} ${q[1]}`,'none',a,Math.max(.5,w/6)));});pts.forEach(p=>add(circle(p[0],p[1],Math.max(1.5,w/2.5),f)));break;}
 case 'barcode':{let x=0;while(x<100){const b=Math.max(1,rand()*w/2+.8);add(rect(x,0,b,100,rand()>.8?a:f));x+=b+Math.max(1,rand()*w/2+1);}break;}
 case 'datastream':for(let i=0;i<n*2;i++){const x=Math.floor(rand()*10)*10+5,y=rand()*100,L=8+rand()*26;add(path(`M${x} ${y} V${y+L}`,'none',i%3?f:a,Math.max(1,w/3),'stroke-dasharray="3 3"'));}break;
 case 'ditsy':{const bloom=(x,y,r,c)=>{let o='';for(let k=0;k<5;k++){const t=k*2*Math.PI/5-Math.PI/2;o+=circle(x+Math.cos(t)*r,y+Math.sin(t)*r,r*.72,c);}return o+circle(x,y,r*.5,v.background);};for(let i=0;i<Math.max(5,n);i++)add(bloom(rand()*100,rand()*100,w*.5+rand()*w*.35,i%3?f:a));for(let i=0;i<n;i++){const x=rand()*100,y=rand()*100;add(path(`M${x} ${y} q5 -5 10 -1 q-6 6 -10 1 Z`,a,'none',0));}break;}
 case 'daisy':{const dz=(x,y,r,c)=>{let o='';for(let k=0;k<8;k++){const t=k*Math.PI/4,px=x+Math.cos(t)*r*.62,py=y+Math.sin(t)*r*.62;o+=`<ellipse cx="${px}" cy="${py}" rx="${r*.42}" ry="${r*.19}" fill="${c}" transform="rotate(${t*180/Math.PI} ${px} ${py})"/>`;}return o+circle(x,y,r*.3,a);};for(const [x,y,r] of [[25,25,15],[75,75,15],[75,25,10],[25,75,10]])add(dz(x,y,r,f));break;}
 case 'rosebud':{const rose=(x,y,r,c)=>{let d=`M${x} ${y}`;for(let k=1;k<=34;k++){const t=k*.4,rr=r*k/34;d+=` L${x+Math.cos(t)*rr} ${y+Math.sin(t)*rr}`;}return path(d,'none',c,Math.max(1.4,w/2.2));};for(const [x,y,r,c] of [[28,28,13,f],[78,78,13,f],[78,28,9,a],[28,78,9,a]])add(rose(x,y,r,c));break;}
 case 'tulip':{const tp=(x,y,z,c)=>`<g transform="translate(${x} ${y}) scale(${z})">${path('M0 0 C-9 -4 -10 -16 -7 -23 C-4 -14 -3 -13 0 -20 C3 -13 4 -14 7 -23 C10 -16 9 -4 0 0 Z',c,'none',0)}${path('M0 0 V17 M0 8 q-9 -2 -11 -10 q10 -1 11 10 M0 12 q9 -2 11 -10 q-10 -1 -11 10','none',a,Math.max(1,w/4))}</g>`;add(tp(25,34,1,f));add(tp(75,84,1,f));add(tp(75,34,.72,a));add(tp(25,84,.72,a));break;}
 case 'sakura':{const bl=(x,y,r,c)=>{let o='';for(let k=0;k<5;k++){const t=k*2*Math.PI/5-Math.PI/2,px=x+Math.cos(t)*r*.7,py=y+Math.sin(t)*r*.7;o+=`<ellipse cx="${px}" cy="${py}" rx="${r*.52}" ry="${r*.44}" fill="${c}" transform="rotate(${t*180/Math.PI+90} ${px} ${py})"/>`;}for(let k=0;k<5;k++){const t=k*2*Math.PI/5-Math.PI/2;o+=path(`M${x} ${y} L${x+Math.cos(t)*r*.45} ${y+Math.sin(t)*r*.45}`,'none',a,Math.max(.6,w/6));}return o+circle(x,y,r*.2,a);};for(const [x,y,r,c] of [[22,26,14,f],[72,74,14,f],[82,22,9,a],[30,80,9,a]])add(bl(x,y,r,c));break;}
 case 'sunflower':{const sf=(x,y,r,c)=>{let o='';for(let k=0;k<14;k++){const t=k*Math.PI/7,px=x+Math.cos(t)*r*.75,py=y+Math.sin(t)*r*.75;o+=`<ellipse cx="${px}" cy="${py}" rx="${r*.4}" ry="${r*.16}" fill="${c}" transform="rotate(${t*180/Math.PI} ${px} ${py})"/>`;}o+=circle(x,y,r*.42,a);for(let k=0;k<8;k++)o+=circle(x+Math.cos(k*2.4)*r*.22,y+Math.sin(k*2.4)*r*.22,r*.055,v.background);return o;};add(sf(30,30,20,f));add(sf(80,80,20,f));break;}
 case 'poppy':{const pp=(x,y,r,c)=>{let o='';for(let k=0;k<4;k++){const t=k*Math.PI/2+.4;o+=path(`M${x} ${y} Q${x+Math.cos(t-.55)*r*1.3} ${y+Math.sin(t-.55)*r*1.3} ${x+Math.cos(t)*r} ${y+Math.sin(t)*r} Q${x+Math.cos(t+.55)*r*1.3} ${y+Math.sin(t+.55)*r*1.3} ${x} ${y} Z`,c,'none',0);}return o+circle(x,y,r*.22,a);};add(pp(28,30,16,f));add(pp(78,80,16,f));add(pp(82,26,10,a));break;}
 case 'lotus':{const lt=(x,y,z,c)=>{let o='';for(let k=-2;k<=2;k++){const t=k*.5;o+=path(`M${x} ${y} Q${x+Math.sin(t)*z*1.5-Math.cos(t)*7} ${y-z*.7} ${x+Math.sin(t)*z} ${y-z*1.3} Q${x+Math.sin(t)*z*1.5+Math.cos(t)*7} ${y-z*.7} ${x} ${y} Z`,'none',c,Math.max(1,w/4));}return o;};add(lt(25,72,20,f));add(lt(75,22,20,a));break;}
 case 'vine':for(const y of [25,75]){add(path(`M0 ${y} C15 ${y-14} 35 ${y+14} 50 ${y} S85 ${y-14} 100 ${y}`,'none',f,Math.max(1,w/3)));for(let x=6;x<100;x+=14){const up=(Math.round(x/14))%2===0;add(path(`M${x} ${y+(up?-3:3)} q7 ${up?-9:9} 13 ${up?-2:2} q-7 ${up?6:-6} -13 ${up?2:-2} Z`,a,'none',0));}for(let x=13;x<100;x+=28)add(circle(x,y+7,Math.max(1.5,w/3),f));}break;
 case 'meadow':for(let i=0;i<Math.max(7,n*2);i++){const x=rand()*100,h=26+rand()*46,c=i%3?f:a,ty=100-h;add(path(`M${x} 100 C${x+6} ${100-h*.5} ${x-6} ${100-h*.72} ${x} ${ty}`,'none',c,Math.max(.8,w/4)));if(i%2)for(let k=0;k<5;k++){const t=k*2*Math.PI/5;add(circle(x+Math.cos(t)*3.2,ty+Math.sin(t)*3.2,2.4,c));}else add(circle(x,ty,3.2,c));add(path(`M${x} ${100-h*.42} q8 -4 11 -10 q-10 1 -11 10 Z`,a,'none',0));}break;
 case 'chintz':{const bl=(x,y,r,c)=>{let o='';for(let k=0;k<6;k++){const t=k*Math.PI/3,px=x+Math.cos(t)*r*.66,py=y+Math.sin(t)*r*.66;o+=`<ellipse cx="${px}" cy="${py}" rx="${r*.5}" ry="${r*.33}" fill="${c}" transform="rotate(${t*180/Math.PI} ${px} ${py})"/>`;}return o+circle(x,y,r*.32,v.background);};for(let i=0;i<Math.max(5,n);i++)add(bl(rand()*100,rand()*100,6+rand()*7,i%2?f:a));for(let i=0;i<n*2;i++){const x=rand()*100,y=rand()*100;add(path(`M${x} ${y} q6 -7 12 -2 q-7 8 -12 2 Z`,a,'none',0));}break;}
 case 'morris':{add(path('M50 100 C30 76 30 56 50 36 C70 56 70 76 50 100','none',f,Math.max(1,w/3)));add(path('M0 52 C20 32 32 22 50 36 M100 52 C80 32 68 22 50 36','none',f,Math.max(1,w/3)));for(const [x,y,r] of [[30,62,0],[70,62,180],[22,40,-35],[78,40,215],[38,84,-20],[62,84,200],[8,30,-60],[92,30,240]])add(`<g transform="translate(${x} ${y}) rotate(${r})">${path('M0 0 q10 -7 15 -1 q-9 9 -15 1 Z',a,'none',0)}</g>`);for(const [x,y] of [[50,22],[50,58],[0,52],[100,52]]){for(let k=0;k<6;k++){const t=k*Math.PI/3;add(circle(x+Math.cos(t)*4.6,y+Math.sin(t)*4.6,3.4,f));}add(circle(x,y,2.6,a));}break;}
 case 'tropical':{const lf=(x,y,z,c,r)=>`<g transform="translate(${x} ${y}) rotate(${r}) scale(${z})">${path('M0 22 C-16 12 -18 -8 0 -23 C18 -8 16 12 0 22 Z','none',c,Math.max(1,w/4))}${path('M0 20 V-20 M0 -12 l-11 -4 M0 -12 l11 -4 M0 -2 l-13 -3 M0 -2 l13 -3 M0 8 l-11 -1 M0 8 l11 -1','none',c,Math.max(.6,w/6))}</g>`;add(lf(28,30,1,f,-20));add(lf(78,78,1,f,25));add(lf(82,24,.7,a,62));add(lf(22,80,.7,a,-68));break;}
 case 'lavender':for(const [x,c] of [[18,f],[50,a],[82,f]])for(const y0 of [0,50]){add(path(`M${x} ${y0+46} C${x+4} ${y0+34} ${x-4} ${y0+24} ${x} ${y0+11}`,'none',a,Math.max(.8,w/4)));for(let k=0;k<7;k++)add(`<ellipse cx="${x+(k%2?2.6:-2.6)}" cy="${y0+9+k*4.4}" rx="2.3" ry="3.4" fill="${c}"/>`);}break;
 case 'blossom':{add(path('M0 70 C25 60 40 40 60 42 C80 44 90 30 100 20','none',f,Math.max(1,w/3)));const b=(x,y,r,c)=>{let o='';for(let k=0;k<5;k++){const t=k*2*Math.PI/5;o+=circle(x+Math.cos(t)*r*.8,y+Math.sin(t)*r*.8,r*.55,c);}return o+circle(x,y,r*.32,a);};for(const [x,y,r] of [[18,64,7],[45,45,8],[72,38,6],[93,24,7]])add(b(x,y,r,f));for(const [x,y] of [[32,55],[58,42],[84,30]])add(path(`M${x} ${y} q8 -7 13 -1 q-8 8 -13 1 Z`,a,'none',0));break;}
 case 'posy':{const ps=(x,y,z,c)=>{let o='';for(let k=0;k<3;k++){const t=-Math.PI/2+(k-1)*.7,bx=x+Math.cos(t)*10*z,by=y+Math.sin(t)*10*z;o+=path(`M${x} ${y+11*z} Q${bx} ${y} ${bx} ${by}`,'none',a,Math.max(.8,w/5));for(let m=0;m<5;m++){const tt=m*2*Math.PI/5;o+=circle(bx+Math.cos(tt)*3.4*z,by+Math.sin(tt)*3.4*z,2.6*z,k===1?c:a);}o+=circle(bx,by,1.7*z,v.background);}return o;};add(ps(25,32,1,f));add(ps(75,82,1,f));break;}
 case 'custom':{const shape=(x,y,c)=>{const r=w*1.8;switch(v.customShape){case 'circle':return circle(x,y,r,c);case 'square':return rect(x-r,y-r,r*2,r*2,c);case 'diamond':return poly(`${x},${y-r} ${x+r},${y} ${x},${y+r} ${x-r},${y}`,c);case 'triangle':return poly(`${x},${y-r} ${x+r},${y+r} ${x-r},${y+r}`,c);case 'star':return star(x,y,r,5,c);case 'cross':return path(`M${x-r} ${y} H${x+r} M${x} ${y-r} V${y+r}`,'none',c,w);case 'heart':return heart(x,y,r,c);case 'hexagon':return poly(Array.from({length:6},(_,i)=>`${x+Math.cos(i*Math.PI/3)*r},${y+Math.sin(i*Math.PI/3)*r}`).join(' '),c);case 'text':return `<text x="${x}" y="${y}" text-anchor="middle" dominant-baseline="central" font-family="sans-serif" font-size="${w*3}" fill="${c}">${esc(v.customText||'✦')}</text>`;}};if(v.customLayout==='scatter'){for(let i=0;i<n;i++)add(shape(rand()*100,rand()*100,i%2?f:a));}else if(v.customLayout==='brick'){for(const [x,y] of [[0,25],[50,25],[25,75],[75,75]])add(shape(x,y,y===25?f:a));}else add(shape(50,50,f));break;}
 }return out;
}
function svg(v,w='100%',h='100%',options={}){const id=options.id||'pattern',scale=(v.scale/100)*(options.zoom||1),space=1-v.spacing/100,mirror=v.mirror?`translate(100 0) scale(-1 1)`:'',tile=options.tile;const rotation=tile?0:v.rotation,ox=tile?0:v.offsetX,oy=tile?0:v.offsetY;let content=`<g id="${id}-motif" opacity="${v.opacity/100}" transform="translate(${50*(1-space)} ${50*(1-space)}) scale(${space})"><g transform="${mirror}">${motif(v)}</g></g>`;content+=`<pattern id="${id}" width="100" height="100" patternUnits="userSpaceOnUse" patternTransform="translate(${ox} ${oy}) rotate(${rotation}) scale(${scale})">`;for(let y=-1;y<=1;y++)for(let x=-1;x<=1;x++)content+=`<use href="#${id}-motif" x="${x*100}" y="${y*100}"/>`;if(options.guides)content+='<rect x="0" y="0" width="100" height="100" fill="none" stroke="#ef3576" stroke-width="1" stroke-dasharray="4 4"/>';content+='</pattern>';return `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}"${tile?` viewBox="0 0 ${v.scale} ${v.scale}"`:''}><defs>${content}</defs>${v.transparent?'':`<rect width="100%" height="100%" fill="${v.background}"/>`}<rect width="100%" height="100%" fill="url(#${id})"/></svg>`;}
function dataURI(svgText){return 'data:image/svg+xml,'+encodeURIComponent(svgText).replace(/'/g,'%27').replace(/\(/g,'%28').replace(/\)/g,'%29');}
function css(){return `background-color: ${s.transparent?'transparent':s.background};\nbackground-image: url("${dataURI(svg(s))}");\nbackground-repeat: no-repeat;\nbackground-size: 100% 100%;`;}
function render(){const p=patterns.find(p=>p[0]===s.pattern);$('art').innerHTML=svg(s,'100%','100%',{zoom,guides:$('guides').checked});$('patternName').textContent=p[1].toUpperCase();$('previewInfo').textContent=`${s.scale} px · ${s.rotation}° · ${s.transparent?'transparent':'seamless'}`;$('family').textContent=p[2];$('patternDescription').textContent=p[3];$('customControls').hidden=s.pattern!=='custom';$('customText').hidden=$('customTextLabel').hidden=s.customShape!=='text';$('mockup').hidden=!$('showMockup').checked;for(const id of ['scale','rotation','weight','density','spacing','opacity'])$(id+'Out').value=s[id]+({scale:' px',rotation:'°',spacing:'%',opacity:'%'}[id]||'');$('codeLabel').textContent=format.toUpperCase();$('code').textContent=format==='css'?css():svg(s,...size());const fixedDensity=['dots','polka','staggered','stripes','diagonal','grid','checker','diamonds','triangles','hexagons','cubes','chevron','zigzag','crosses','pluses','rings','arches','scales','gingham','plaid','tartan','herringbone','basket','weave','houndstooth','argyle','pinstripe','knit','stitch','waves','scallops','stars','hearts','flowers','leaves','quatrefoil','moroccan','greekkey','maze','truchet','circuit'];$('density').disabled=fixedDensity.includes(s.pattern)||(s.pattern==='custom'&&s.customLayout!=='scatter');$('weight').disabled=['checker','diamonds','triangles','cubes','gingham','herringbone','basket','weave','houndstooth','leaves'].includes(s.pattern);$('seed').disabled=$('reseed').disabled=!['tweed','terrazzo','confetti','noise','speckle','bubbles','pebbles','maze','truchet'].includes(s.pattern)&&!(s.pattern==='custom'&&s.customLayout==='scatter');}
function sync(){for(const [id,key] of [['foreground','foreground'],['background','background'],['accentColor','accent']])setColor(id,s[key]);for(const id of Object.keys(ranges))$(id).value=s[id];for(const id of ['mirror','transparent'])$(id).checked=s[id];for(const id of ['customShape','customText','customLayout'])$(id).value=s[id];}
function renderLibrary(){const q=$('search').value.toLowerCase().trim();const list=patterns.filter(p=>(category==='All'||p[2]===category)&&p.join(' ').toLowerCase().includes(q));$('library').innerHTML=list.length?list.map(p=>`<button class="pattern-card ${p[0]===s.pattern?'active':''}" data-pattern="${p[0]}" aria-pressed="${p[0]===s.pattern}" title="${esc(p[1]+': '+p[3])}"><span class="thumb"><img alt="" loading="lazy" style="width:100%;height:100%;object-fit:cover" src="${dataURI(svg({...initial,pattern:p[0],scale:46,weight:6,foreground:'#7f8b7a',background:'#f3f1e9',accent:'#bcc3ae'},80,65))}"></span><span>${esc(p[1])}</span></button>`).join(''):'<div class="empty library-empty">No patterns found. Try another name or category.</div>';$('patternCount').textContent=`${list.length} of ${patterns.length} patterns · infinitely adjustable`;$('libraryTotal').textContent=patterns.length+' PATTERNS';}
$('categories').innerHTML=categoryList().map(c=>`<button data-category="${c}" class="${c===category?'active':''}" aria-pressed="${c===category}">${c}</button>`).join('');$('categories').onclick=e=>{if(!e.target.dataset.category)return;category=e.target.dataset.category;[...$('categories').children].forEach(b=>{b.classList.toggle('active',b.dataset.category===category);b.setAttribute('aria-pressed',b.dataset.category===category);});renderLibrary();};$('search').oninput=renderLibrary;$('library').onclick=e=>{const b=e.target.closest('[data-pattern]');if(!b)return;s.pattern=b.dataset.pattern;render();[...$('library').children].forEach(el=>{el.classList.toggle('active',el.dataset.pattern===s.pattern);el.setAttribute('aria-pressed',el.dataset.pattern===s.pattern);});hist.push();};
for(const [id,key] of [['foreground','foreground'],['background','background'],['accentColor','accent']])bindColor(id,c=>{s[key]=c;render();hist.push();});for(const [id,[lo,hi]] of Object.entries(ranges)){$(id).oninput=()=>{s[id]=clamp($(id).value,lo,hi);if(['density','seed'].includes(id))s[id]=Math.round(s[id]);render();};$(id).onchange=()=>{sync();hist.push();};}for(const id of ['mirror','transparent'])$(id).onchange=()=>{s[id]=$(id).checked;render();hist.push();};for(const id of ['customShape','customText','customLayout'])$(id).onchange=()=>{s[id]=$(id).value;render();hist.push();};$('swapColors').onclick=()=>{[s.foreground,s.background]=[s.background,s.foreground];sync();render();hist.push();};$('invertColors').onclick=()=>{for(const key of ['foreground','background','accent'])s[key]=hex(...rgb(s[key]).map(v=>255-v));sync();render();hist.push();};
$('schemes').innerHTML=schemes.map(([name,f,b,a],i)=>`<button class="pattern-palette" data-scheme="${i}" title="${name}" aria-label="${name} color palette"><i style="background:${f}"></i><i style="background:${b}"></i><i style="background:${a}"></i></button>`).join('');$('schemes').onclick=e=>{const b=e.target.closest('[data-scheme]');if(!b)return;[,s.foreground,s.background,s.accent]=schemes[+b.dataset.scheme];sync();render();hist.push();};$('reseed').onclick=()=>{s.seed=1+Math.floor(Math.random()*999999);sync();render();hist.push();};$('randomize').onclick=()=>{s.pattern=patterns[Math.floor(Math.random()*(patterns.length-1))][0];const scheme=schemes[Math.floor(Math.random()*schemes.length)];[,s.foreground,s.background,s.accent]=scheme;s.seed=1+Math.floor(Math.random()*999999);s.rotation=[0,0,0,45,90][Math.floor(Math.random()*5)];s.scale=40+Math.round(Math.random()*100);sync();render();renderLibrary();hist.push();};$('reset').onclick=()=>{s=structuredClone(initial);sync();render();renderLibrary();hist.push();};$('zoom').onchange=()=>{zoom=+$('zoom').value;render();};$('showMockup').onchange=$('guides').onchange=render;$('fullscreen').onclick=fullScreen;
$('codeTabs').onclick=e=>{if(!e.target.dataset.format)return;format=e.target.dataset.format;[...$('codeTabs').children].forEach(b=>b.classList.toggle('active',b.dataset.format===format));render();};$('copyCode').onclick=()=>copy(format==='css'?css():svg(s,...size()));$('exportW').onchange=$('exportH').onchange=()=>{size();render();};$('exportCSS').onclick=()=>download('.pattern-background {\n  '+css().replace(/\n/g,'\n  ')+'\n}\n','pattern.css','text/css');$('exportSVG').onclick=()=>{download(svg(s,...size()),s.pattern+'.svg','image/svg+xml');toast('Vector SVG exported');};$('exportTile').onclick=()=>{download(svg(s,s.scale,s.scale,{tile:true}),s.pattern+'-tile.svg','image/svg+xml');toast('Seamless base tile exported (unrotated, without offsets)');};
$('exportPNG').onclick=async()=>{const btn=$('exportPNG');btn.disabled=true;let url;try{const [w,h]=size(),source=svg(s,w,h),canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const img=new Image();url=URL.createObjectURL(new Blob([source],{type:'image/svg+xml'}));await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=reject;img.src=url;});canvas.getContext('2d').drawImage(img,0,0,w,h);await canvasBlob(canvas,s.pattern+'.png');}catch{toast('Export failed. Try a smaller image or export SVG.');}finally{if(url)URL.revokeObjectURL(url);btn.disabled=false;}};
function renderSaved(){saved=saved.filter(v=>{try{validate(v.state);return typeof v.name==='string';}catch{return false;}}).slice(0,30);$('savedCount').textContent=saved.length;$('saved').innerHTML=saved.length?saved.map((v,i)=>`<div class="saved-item"><button class="saved-load" data-load="${i}"><i style="background:${v.state.foreground}"></i>${esc(v.name)}</button><button data-delete="${i}" aria-label="Delete saved pattern ${i+1}">×</button></div>`).join(''):'<div class="empty">Save your favorite recipes here.</div>';}
$('save').onclick=()=>{if(saved.length>=30){toast('Library full (30). Export projects or remove a saved pattern.');return;}saved.unshift({name:patterns.find(p=>p[0]===s.pattern)[1]+' · '+new Date().toLocaleDateString(),state:structuredClone(s)});if(write('bt-pattern-saved',saved))toast('Pattern saved to this browser');renderSaved();};$('saved').onclick=e=>{const b=e.target.closest('[data-load]');if(b){apply(saved[+b.dataset.load].state);hist.push();toast('Pattern restored');}if(e.target.dataset.delete!==undefined){saved.splice(+e.target.dataset.delete,1);write('bt-pattern-saved',saved);renderSaved();}};$('exportProject').onclick=()=>download(JSON.stringify(s,null,2),'pattern-studio.json','application/json');$('importProject').onchange=()=>{readJSON($('importProject').files[0],v=>{apply(validate(v));hist.push();});$('importProject').value='';};sync();render();renderLibrary();renderSaved();
})();
